export const MAX_QR_PAYLOAD_LENGTH = 12000;
export const MAX_JWT_LENGTH = 12000;
export const MAX_CREDENTIAL_IMPORT_SIZE = 20000;
export const MAX_PRESENTATION_CREDENTIALS = 10;
export const MAX_JSON_PARSE_DEPTH = 10;

export const SUPPORTED_JWT_ALGS = ['ES256', 'EdDSA'] as const;
export const SUPPORTED_JWT_ALG = SUPPORTED_JWT_ALGS;

export type SupportedJwtAlg = (typeof SUPPORTED_JWT_ALGS)[number];

export const SECURITY_LIMITS = {
  MAX_QR_PAYLOAD_LENGTH,
  MAX_JWT_LENGTH,
  MAX_CREDENTIAL_IMPORT_SIZE,
  MAX_PRESENTATION_CREDENTIALS,
  MAX_JSON_PARSE_DEPTH,
  SUPPORTED_JWT_ALGS,
  SUPPORTED_JWT_ALG,
} as const;